server:
  port: 8082
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
      - id: poke-service
        uri: http://poke-service:8081
        predicates:
          - Path=/api/v1/**